// Generated by CoffeeScript 1.6.3
(function() {
  (function($) {
    return $('body').keyup(function(e) {
      var comment;
      comment = $('.mentions-input-box textarea');
      if (e.keyCode !== 27) {
        return;
      }
      if (comment.lenght === 0) {
        return;
      }
      if (comment.val().length === 0) {
        return;
      }
      if (!confirm('Comment is not empty, are you sure?')) {
        return false;
      }
    });
  })(jQuery);

}).call(this);
